spring:
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-consumer-group

server:
  port: 8082

---
# Optional overrides for the "local" profile
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      # Override or repeat settings for the local profile if needed
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-consumer-group-local
